### ISSUE TITLE
npm conflicts

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#178]
Since commit:[a4112ea](https://github.com/postcss/postcss.org/commit/a4112eac65a550b14034b7d4d656ed194d023e74) there seems to be troubles/conflicts with the npm packages. Try reinstall modules `package.json` to troubleshoot the errors.

@MoOx / @thangngoc89

**Comment by MoOx** [comment]
I am taking a look.

**Comment by marcustisater** [comment]
It's wired. 

This [commit](https://github.com/thangngoc89/postcss.org/commit/2b7554226a17fd84511652694be085f1c1ea2cdb) passed and got merged into master.

**Comment by MoOx** [comment]
It seems it has nothing to do with npm itself.

https://github.com/postcss/postcss.org/tree/master/web_modules/App this image should be here https://github.com/postcss/postcss.org/tree/master/web_modules/LayoutContainer

btw, on hard drive non case sensitive, we got issue because of the web_modules/app || App

**Comment by marcustisater** [comment]
Nice catch, I resolved [that](https://github.com/postcss/postcss.org/commit/92fd1b745820a22873b8b9cd4293696f3484e586) 

It says that Statinamic required babel-plugin-webpack-loaders `0.3.2`, we have `0.2.2`. 

Does this ring a bell?

```
postcss.org/node_modules/statinamic/lib/configurator/index.js:108
  if (!config.baseUrl.pathname.endsWith("/"))
```

**Comment by MoOx** [comment]
You can upgrade safely to 0.3.2.

**Comment by marcustisater** [comment]
Ok great, I will do that right away but that did not resolve my following error when running `npm start` locally. Is everything working for you?

```
postcss.org/node_modules/statinamic/lib/configurator/index.js:108
  if (!config.baseUrl.pathname.endsWith("/"))
```

**Comment by thangngoc89** [comment]
What's wrong with 

```
postcss.org/node_modules/statinamic/lib/configurator/index.js:108
  if (!config.baseUrl.pathname.endsWith("/"))
```

Could you provide full stack-trace

**Comment by MoOx** [comment]
You can found it on travis ci.
Anyway, it seems that master is ok? 
npm start works like a charm for me.

**Comment by thangngoc89** [comment]
Totally forgot that npm 2 will throw error about unmet peerDeps.

**Comment by marcustisater** [comment]
Yeah, master is fine [now](https://github.com/postcss/postcss.org/pull/181) probably unmet peerDeps as @thangngoc89 says.

Sorry, here is the error logg;

```
/Applications/postcss.org/node_modules/statinamic/lib/configurator/index.js:108
  if (!config.baseUrl.pathname.endsWith("/")) {
                               ^
TypeError: undefined is not a function
    at config (/Applications/postcss.org/node_modules/statinamic/lib/configurator/index.js:108:32)
    at Object.<anonymous> (config.js:4:16)
    at Module._compile (module.js:460:26)
    at loader (/Applications/postcss.org/node_modules/babel-core/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Applications/postcss.org/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Applications/postcss.org/scripts/webpack.config.babel.js:23:15)
/Applications/postcss.org/node_modules/babel-core/lib/transformation/file/index.js:585
      throw err;
            ^
Error: /Applications/postcss.org/web_modules/layouts/HomePage/index.js: Command failed: node /Applications/postcss.org/node_modules/webpack/bin/webpack.js /Applications/postcss.org/web_modules/layouts/HomePage/index.css /Applications/postcss.org/dist/.webpack.res.1455602553283_447605.js --config ./scripts/webpack.config.babel.js --colors --bail
/Applications/postcss.org/node_modules/statinamic/lib/configurator/index.js:108
  if (!config.baseUrl.pathname.endsWith("/")) {
                               ^
TypeError: undefined is not a function
    at config (/Applications/postcss.org/node_modules/statinamic/lib/configurator/index.js:108:32)
    at Object.<anonymous> (config.js:4:16)
    at Module._compile (module.js:460:26)
    at loader (/Applications/postcss.org/node_modules/babel-core/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Applications/postcss.org/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Applications/postcss.org/scripts/webpack.config.babel.js:23:15)

    at checkExecSyncError (child_process.js:1346:13)
    at execSync (child_process.js:1386:13)
    at exports.default (/Applications/postcss.org/node_modules/babel-plugin-webpack-loaders/lib/runWebPackSync.js:41:51)
    at PluginPass.CallExpression (/Applications/postcss.org/node_modules/babel-plugin-webpack-loaders/lib/plugin.js:76:60)
    at newFn (/Applications/postcss.org/node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:293:19)
    at NodePath._call (/Applications/postcss.org/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:74:18)
    at NodePath.call (/Applications/postcss.org/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:46:17)
    at NodePath.visit (/Applications/postcss.org/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:104:12)
    at TraversalContext.visitQueue (/Applications/postcss.org/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:156:16)
    at TraversalContext.visitSingle (/Applications/postcss.org/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:113:19)
    at TraversalContext.visit (/Applications/postcss.org/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:200:19)
```

**Comment by marcustisater** [comment]
Hmm, still troubleshooting. I ran

```
rm -rf node_modules
rm -rf ~/.npm
npm cache clear
npm install
npm start
```

**Comment by MoOx** [comment]
You got the same issue?

**Comment by thangngoc89** [comment]
I can't reproduce at all

**Comment by marcustisater** [comment]
Yeah, I was trying to scout for some people to reinstall the modules too and hope they catch the same error as well but something is probably wrong here locally. I will try reinstall npm and node. 

```
npm 3.7.2
node v0.12.7
```

**Comment by thangngoc89** [comment]
@marcustisater that's your problem :( 

node 0.12.7 doesn't have a endsWith method

**Comment by marcustisater** [comment]
so update node? :smile:

**Comment by thangngoc89** [comment]
Yup. 5.6.0 is the latest (you can use nvm to have multiple node version )

**Comment by marcustisater** [comment]
oh haha, I've been outdated for a while.

**Comment by marcustisater** [comment]
ok everything is working but it's a bit slow on v5.6.0

Thanks for the help. back to work :)

**Comment by MoOx** [comment]
Only npm install should be slower (but smarter). Is this the case?

**Comment by marcustisater** [comment]
No, it takes a while to fire up statinamtic.

**Comment by MoOx** [comment]
For me it tooks around 10sec.

**Comment by marcustisater** [comment]
The first build took a minute to load, now it only takes 10-15 seconds. Solved :wink:

**Comment by MoOx** [comment]
Ok, it's due to babel cache :)
