### ISSUE TITLE
Script build broken

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#220]
Any ideas? Using node v6.4.0 and npm 3.10.6

```
module.js:457
    throw err;
    ^

Error: Cannot find module '/Applications/postcss.org/Applications/postcss.org/node_modules/.bin/phenomic'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/postcss.org/node_modules/phenomic/lib/bin/runner-cmd.js:12:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

@thangngoc89 ?

**Comment by thangngoc89** [comment]
Eh no idea. Could you remove and reinstall node_modules?
