### ISSUE TITLE
Phenomic update

### ISSUE THREAD

**Issue by marcustisater** [postcss/postcss.org#221]
We need to update Phenomic from `0.10` to `0.16.2`

**Comment by halvves** [comment]
I have issued a pull req to update to 0.14.0 first. I've been running into some issues updating to 0.16.2. When I `npm start` after updating to 0.16.2 I get the following error:

```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1148:7)
    at setopts (/Users/halvves/dev/opensource/postcss.org/node_modules/phenomic/node_modules/glob/common.js:97:21)
    at new GlobSync (/Users/halvves/dev/opensource/postcss.org/node_modules/phenomic/node_modules/glob/sync.js:40:3)
    at Function.globSync [as sync] (/Users/halvves/dev/opensource/postcss.org/node_modules/phenomic/node_modules/glob/sync.js:26:10)
    at /Users/halvves/dev/opensource/postcss.org/node_modules/phenomic/node_modules/globby/index.js:78:35
    at Array.reduce (native)
    at module.exports.sync (/Users/halvves/dev/opensource/postcss.org/node_modules/phenomic/node_modules/globby/index.js:77:19)
    at offlinePlugin (/Users/halvves/dev/opensource/postcss.org/node_modules/phenomic/lib/_utils/offline/webpack.js:31:33)
    at exports.default (/Users/halvves/dev/opensource/postcss.org/node_modules/phenomic/lib/builder/webpack/config.browser.js:30:113)
```

I've found a few other instances of that problem online. All relevant conversations recommended updating various webpack loaders/plugins. I tried updating just about everything to no avail. @MoOx, @thangngoc89, any thoughts?

**Comment by marcustisater** [comment]
Yeah if someone could dig into this problem that would be great. We are kind of stuck here.

**Comment by marcustisater** [comment]
See https://github.com/postcss/postcss.org/pull/223

**Comment by MoOx** [comment]
I responded over there.

**Comment by marcustisater** [comment]
life saver, thanks man.
