### ISSUE TITLE
Yarn error with postcss: ERR_INVALID_FILE_URL_PATH

### ISSUE THREAD

**Issue by andry900** [postcss/postcss.org#281]
I have been experiencing this error for a few weeks, I also found another report for the same problem in this incident: [PostCSS incident](https://github.com/italia/design-react-kit/issues/862) but it still has no answers.

Since the problem is very impactful as it no longer allows me to work on the project, I would like to know as soon as possible how to solve it.
3 of us are working on this project, my colleagues who use PC with MacOS as operating system have no problems, it happens only on my PC with Windows.

This is the error trace after executing the **yarn start** command:
`Starting the development server...

C:\Users\XXX\projects\YYY\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

TypeError: File URL path must be absolute
    at new NodeError (node:internal/errors:387:5)
    at getPathFromURLWin32 (node:internal/url:1407:11)
    at fileURLToPath (node:internal/url:1437:22)
    at Input.origin (C:\Users\XXX\projects\YYY\node_modules\react-scripts\node_modules\postcss\lib\input.js:202:23) 
    at Input.error (C:\Users\XXX\projects\YYY\node_modules\react-scripts\node_modules\postcss\lib\input.js:133:23)  
    at Declaration.error (C:\Users\XXX\projects\YYY\node_modules\react-scripts\node_modules\postcss\lib\node.js:60:32)
    at Warning.toString (C:\Users\XXX\projects\YYY\node_modules\react-scripts\node_modules\postcss\lib\warning.js:21:24)
    at new Error (<anonymous>)
    at new Warning (C:\Users\XXX\projects\YYY\node_modules\react-scripts\node_modules\postcss-loader\dist\Warning.js:15:5)
    at Object.loader (C:\Users\XXX\projects\YYY\node_modules\react-scripts\node_modules\postcss-loader\dist\index.js:149:22) {
  code: 'ERR_INVALID_FILE_URL_PATH'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by ai** [comment]
1. Seems like you need to open an issue in `postcss/postcss` not in PostCSS website repo
2. This PR may be relevant to your problem https://github.com/postcss/postcss/pull/1788
